services:
  master-server:
    build:
      context: master/server
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./master/server:/usr/src/app
    networks:
      - app-network

  secondary-server:
    build:
      context: secondary/server
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - ./secondary/server:/usr/src/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge